extends SceneTree
const Model = preload("res://demo08_3d/paper_model.gd")
var failures := 0
func check(ok:bool,message:String)->void:
	print(("PASS: " if ok else "FAIL: ")+message)
	if not ok: failures+=1
func _initialize()->void:
	var model=Model.new()
	var area:float=model.paper.material_area()
	check(model.begin_crease(0,Vector3(0,0,-0.15),Vector3(0,0,0.15)),"begin explicit crease transaction")
	check(model.select_feature(0) and model.features.size()==1,"reselecting pending crease preserves preview transaction")
	if model.features.is_empty(): print("WORKBENCH_MODEL_RESULT failures=%d"%failures);quit(1);return
	check(model.preview_angle(PI/3),"preview partial angle")
	check(model.commit(),"commit first hinge")
	var face_idx:int=model.paper.history.back().moves.find(true)
	var uv:PackedVector2Array=model.paper.material_faces[face_idx]
	var a:Vector2=uv[0].lerp(uv[1],0.5)
	var b:Vector2=uv[2].lerp(uv[3],0.5)
	check(model.begin_crease(face_idx,model.material_to_world(face_idx,a),model.material_to_world(face_idx,b)),"second crease on standing face")
	model.preview_angle(-PI/4);model.commit()
	check(model.features.size()==2,"two editable crease features")
	var before:Array=model.paper.faces.duplicate(true)
	check(model.select_feature(0) and model.preview_angle(PI/6),"edit first hinge after second fold")
	check(model.paper.faces!=before and absf(model.paper.material_area()-area)<0.000001,"descendants replay and area preserved")
	model.cancel()
	check(model.paper.faces==before,"cancel restores all geometry and angles")
	model.select_feature(0);model.preview_angle(PI/6);model.commit()
	var edited:Array=model.paper.faces.duplicate(true)
	check(model.undo() and model.paper.faces==before,"undo is a whole model transaction")
	check(model.redo() and model.paper.faces==edited,"redo restores changed ancestor and children")
	check(not model.preview_angle(NAN),"reject NaN angles")
	check(not model.begin_crease(0,Vector3.ZERO,Vector3.ZERO),"reject degenerate hinge without mutation")
	check(model.paper.faces==edited,"invalid crease leaves last good model")
	check(model.load_dart() and model.features.size()==1 and not model.paper.is_flat(),"flying starter has editable wing hinge")
	check(model.select_feature(0) and model.preview_angle(deg_to_rad(30)),"starter wing angle is editable")
	model.cancel()
	check(absf(rad_to_deg(float(model.features[0].angle))-14)<0.001,"starter cancellation restores wing angle")
	var starter_shape:Array=model.paper.faces.duplicate(true)
	model.new_sheet()
	check(model.features.is_empty() and model.paper.faces.size()==1,"new sheet creates clean editable paper")
	check(model.undo() and model.paper.faces==starter_shape,"new sheet is undoable without losing starter")
	model.select_feature(0)
	check(not model.preview_angle(NAN) and model.paper.faces==starter_shape,"NaN inside an active transaction preserves geometry")
	model.cancel()
	print("WORKBENCH_MODEL_RESULT failures=%d"%failures)
	quit(0 if failures==0 else 1)
